version: "3.9"
   
services:
  web:
    build: .
    environment:
      MYENV: EXAMPLE
    volumes:
      - .:/code
  web_makemigrations:
    extends:
      service: web
    command: python SUML_IF_Project/manage.py makemigrations
  web_migrate:
    extends:
      service: web
    command: python SUML_IF_Project/manage.py migrate
  web_run:
    extends:
      service: web
    command: python SUML_IF_Project/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"