# Generated by Django 4.0.1 on 2022-01-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diabetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sick', models.BooleanField(null=True)),
                ('high_blood_preasure', models.CharField(choices=[(1, 'HighBloodPreasure'), (0, 'LowBloodPreasure')], max_length=1, null=True)),
                ('cholesterol', models.CharField(choices=[(1, 'HighCholesterol'), (0, 'LowCholesterol')], max_length=1, null=True)),
            ],
        ),
    ]
