# Generated by Django 4.0.1 on 2022-01-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diviner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diabetes',
            name='bmi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='cholesterol',
            field=models.IntegerField(choices=[(1, 'HighCholesterol'), (0, 'LowCholesterol')], null=True),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='high_blood_preasure',
            field=models.IntegerField(choices=[(1, 'HighBloodPreasure'), (0, 'LowBloodPreasure')], null=True),
        ),
    ]
