# Generated by Django 4.0.1 on 2022-01-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diviner', '0002_diabetes_bmi_alter_diabetes_cholesterol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetes',
            name='cholesterol',
            field=models.CharField(choices=[(1, 'HighCholesterol'), (0, 'LowCholesterol')], max_length=128, null=True),
        ),
    ]
