# Generated by Django 4.0.1 on 2022-01-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diviner', '0003_alter_diabetes_cholesterol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetes',
            name='cholesterol',
            field=models.IntegerField(choices=[(1, 'HighCholesterol'), (0, 'LowCholesterol')], null=True),
        ),
    ]
