# Generated by Django 4.0.1 on 2022-01-11 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diviner', '0004_alter_diabetes_cholesterol'),
    ]

    operations = [
        migrations.AddField(
            model_name='diabetes',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='diabetes',
            name='education',
            field=models.IntegerField(choices=[(1, 'never attended'), (2, 'kindergarden'), (3, 'primary school'), (4, 'junior high school'), (5, 'high school'), (6, 'college')], null=True),
        ),
        migrations.AddField(
            model_name='diabetes',
            name='general_health_feeling',
            field=models.IntegerField(choices=[(1, 'excellent'), (2, 'very good'), (3, 'good'), (4, 'fair'), (5, 'poor')], null=True),
        ),
        migrations.AddField(
            model_name='diabetes',
            name='healthcare',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='diabetes',
            name='heart_disease_or_attack',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='diabetes',
            name='heavy_alcohol_consumption',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='diabetes',
            name='mental_health_feeling',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='diabetes',
            name='physical_activity',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='diabetes',
            name='physical_health_feeling',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='diabetes',
            name='sex',
            field=models.BooleanField(choices=[(1, 'female'), (0, 'male')], null=True),
        ),
        migrations.AddField(
            model_name='diabetes',
            name='smoker',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='diabetes',
            name='stroke',
            field=models.BooleanField(null=True),
        ),
    ]
