# Generated by Django 4.0.1 on 2022-01-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diviner', '0005_diabetes_age_diabetes_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetes',
            name='age',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='bmi',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='cholesterol',
            field=models.IntegerField(choices=[(1, 'HighCholesterol'), (0, 'LowCholesterol')], default=0),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='education',
            field=models.IntegerField(choices=[(1, 'never attended'), (2, 'kindergarden'), (3, 'primary school'), (4, 'junior high school'), (5, 'high school'), (6, 'college')], default=5),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='general_health_feeling',
            field=models.IntegerField(choices=[(1, 'excellent'), (2, 'very good'), (3, 'good'), (4, 'fair'), (5, 'poor')], default=3),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='healthcare',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='heart_disease_or_attack',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='heavy_alcohol_consumption',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='high_blood_preasure',
            field=models.IntegerField(choices=[(1, 'HighBloodPreasure'), (0, 'LowBloodPreasure')], default=0),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='physical_activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='sex',
            field=models.BooleanField(choices=[(1, 'female'), (0, 'male')], default=False),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='sick',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='smoker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='stroke',
            field=models.BooleanField(default=False),
        ),
    ]
