# Generated by Django 4.0.1 on 2022-01-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diviner', '0006_alter_diabetes_age_alter_diabetes_bmi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetes',
            name='sex',
            field=models.IntegerField(choices=[(1, 'female'), (0, 'male')], default=1),
        ),
    ]
