# Generated by Django 4.0.1 on 2022-01-13 23:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diviner', '0007_alter_diabetes_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetes',
            name='bmi',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='cholesterol',
            field=models.IntegerField(choices=[(1, 'HighCholesterol'), (0, 'LowCholesterol')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='education',
            field=models.IntegerField(choices=[(1, 'never attended'), (2, 'kindergarden'), (3, 'primary school'), (4, 'junior high school'), (5, 'high school'), (6, 'college')], default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='general_health_feeling',
            field=models.IntegerField(choices=[(1, 'excellent'), (2, 'very good'), (3, 'good'), (4, 'fair'), (5, 'poor')], default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='high_blood_preasure',
            field=models.IntegerField(choices=[(1, 'HighBloodPreasure'), (0, 'LowBloodPreasure')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='sex',
            field=models.IntegerField(choices=[(1, 'female'), (0, 'male')], default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='sick',
            field=models.BooleanField(default=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
